services:
  coredashboard:
    container_name: core_dashboard_container
    image: ${DOCKER_REGISTRY-}coredashboard
    build:
      context: ../CoreDashboard
      dockerfile: ../CoreDashboard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - postgres
    ports:
      - 5000:8080
      - 5001:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G

  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_DB: "core_dashboard"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_init/db_restore_script.sh:/docker-entrypoint-initdb.d/db_restore_script.sh
      - ./db_init/core_dashboard.sql:/db_init/core_dashboard.sql
      - core-dashboard-data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d core_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@utmn.ru"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

  grafana:
    container_name: grafana_container
    image: grafana/grafana-enterprise
    restart: unless-stopped
    environment:
      # - GF_DATABASE_TYPE=postgres
      # - GF_DATABASE_HOST=postgres_container:5432
      # - GF_DATABASE_NAME=core_dashboard
      # - GF_DATABASE_USER=postgres
      # - GF_DATABASE_PASSWORD=postgres
      # - GF_DATABASE_SSL_MODE=disable
      - GF_INSTALL_PLUGINS=volkovlabs-variable-panel
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - postgres
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    networks: 
      - postgres


volumes:
  core-dashboard-data:
  pgadmin-data:
  grafana-data:

networks:
  postgres:
    driver: bridge