{
 "title": "Дашборд по студенту",
 "time": { "from": "2024-04-23T18:37:50.978Z", "to": "2024-04-23T18:37:57.610Z" },
 "templating": {
  "list": [
   {
    "name": "uploaded_db_id",
    "label": "Выбранная БД",
    "query": "SELECT uploaded_db_id FROM uploaded_db"
   },
   {
    "name": "student",
    "label": "Студент",
    "query": "SELECT student_name FROM uploaded_db_result dbr\nJOIN student s ON dbr.student_id = s.student_id\nWHERE uploaded_db_id = $uploaded_db_id"
   },
   {
    "name": "study_group",
    "query": "SELECT STRING_AGG(study_group_name, ', ') FROM uploaded_db_result dbr\nJOIN student s ON dbr.student_id = s.student_id\nJOIN study_group sg ON dbr.study_group_id = sg.study_group_id\nWHERE student_name = '$student' AND uploaded_db_id = $uploaded_db_id"
   },
   {
    "name": "discipline",
    "label": "Дисциплина",
    "query": "SELECT reverse(substring(reverse(discipline_name) FROM position(' ' IN reverse(discipline_name)) + 1)) FROM uploaded_db db\nJOIN discipline d ON db.discipline_id = d.discipline_id\nWHERE uploaded_db_id = $uploaded_db_id"
   },
   {
    "name": "semester",
    "label": "Семестр",
    "query": "SELECT reverse(substring(reverse(discipline_name) FROM 1 FOR position(' ' IN reverse(discipline_name)) - 1)) FROM uploaded_db db\nJOIN discipline d ON db.discipline_id = d.discipline_id\nWHERE uploaded_db_id = $uploaded_db_id"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 }, "options": { "content": "# Дашборд по студенту" } },
  {
   "title": "Дисциплина",
   "type": "text",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 2 },
   "options": {
    "content": "# \"$discipline\", $semester семестр"
   }
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 } },
  {
   "title": "Студент",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 7 },
   "options": { "content": "# ${student}\n\n" },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  { "title": "Группа", "type": "text", "gridPos": { "h": 3, "w": 8, "x": 9, "y": 7 }, "options": { "content": "# ${study_group}" } },
  {
   "title": "Итоговый балл",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total_score FROM uploaded_db_result dbr\r\nJOIN student s ON dbr.student_id = s.student_id\r\nWHERE student_name = ${student:sqlstring} AND uploaded_db_id = $uploaded_db_id"
    }
   ]
  },
  {
   "title": "Посещаемость",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE WHEN SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END) = 0 THEN NULL\r\n\tELSE ROUND(SUM(CASE WHEN presence = true THEN 1 ELSE 0 END) * 100.0 / SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END), 2) END AS student_presence_percent\r\nFROM uploaded_db_record dbrec\r\nJOIN uploaded_db_result dbres ON dbrec.uploaded_db_result_id = dbres.uploaded_db_result_id\r\nJOIN student s ON dbres.student_id = s.student_id\r\nWHERE student_name = ${student:sqlstring} AND uploaded_db_id = $uploaded_db_id\r\nGROUP BY student_name"
    }
   ]
  },
  {
   "title": "Успешность выполнения контрольных",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n(\r\n  SELECT control_sum_score FROM\r\n  (\r\n    SELECT s.student_id, SUM(theme_score) as control_sum_score FROM uploaded_db_record dbrec\r\n    JOIN uploaded_db_result dbres ON dbrec.uploaded_db_result_id = dbres.uploaded_db_result_id\r\n    JOIN student s ON dbres.student_id = s.student_id\r\n    WHERE is_control_point = true AND s.student_name = ${student:sqlstring} AND uploaded_db_id = $uploaded_db_id\r\n    GROUP BY s.student_id\r\n  )\r\n) / (SELECT max_control_score FROM max_student_control_score WHERE uploaded_db_id = $uploaded_db_id) * 100"
    }
   ]
  },
  {
   "title": "Итоговая оценка",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT rating FROM uploaded_db_result dbr\r\nJOIN student s ON dbr.student_id = s.student_id\r\nWHERE student_name = ${student:sqlstring} AND uploaded_db_id = $uploaded_db_id\r\nGROUP BY student_name, rating\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Таблица успеваемости",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT pair_theme_name as \"Название темы\",\r\n  pair_type_name as \"Тип пары\",\r\n  is_control_point as \"Контрольная\", \r\n  theme_score as \"Балл\", \r\n  max_score as \"Макс. балл\", \r\n  CASE WHEN max_score = 0 THEN 100 ELSE theme_score * 100 / max_score END as \"Процент от максимума\", \r\n  presence as \"Посещаемость\"\r\nFROM uploaded_db_record dbrec\r\nJOIN uploaded_db_result dbres ON dbrec.uploaded_db_result_id = dbres.uploaded_db_result_id\r\nJOIN student s ON dbres.student_id = s.student_id\r\nJOIN \r\n  (SELECT pt.pair_theme_id, MAX(theme_score) as max_score FROM uploaded_db_record dbrec\r\n  JOIN uploaded_db_result dbres ON dbrec.uploaded_db_result_id = dbres.uploaded_db_result_id\r\n  JOIN pair_theme pt ON dbrec.pair_theme_id = pt.pair_theme_id\r\n  JOIN pair_type ptype ON pt.pair_type_id = ptype.pair_type_id\r\n  GROUP BY pt.pair_theme_id\r\n  ) max_theme_score\r\nON dbrec.pair_theme_id = max_theme_score.pair_theme_id\r\nJOIN pair_theme pt ON dbrec.pair_theme_id = pt.pair_theme_id\r\nJOIN pair_type ptype ON pt.pair_type_id = ptype.pair_type_id\r\nWHERE student_name = ${student:sqlstring} AND uploaded_db_id = $uploaded_db_id\r\nGROUP BY uploaded_db_record_id, pair_theme_name, is_control_point, theme_score, max_score, presence, pair_type_name"
    }
   ]
  }
 ]
}