{
 "title": "Дашборд по группам",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uploaded_db_id",
    "label": "Загруженная БД",
    "query": "select uploaded_db_id from uploaded_db"
   },
   {
    "name": "group_name",
    "label": "Название группы",
    "query": "SELECT study_group_name FROM study_group"
   },
   {
    "name": "discipline",
    "label": "Дисциплина",
    "query": "SELECT reverse(substring(reverse(discipline_name) FROM position(' ' IN reverse(discipline_name)) + 1)) FROM uploaded_db db\nJOIN discipline d ON db.discipline_id = d.discipline_id\nWHERE uploaded_db_id = $uploaded_db_id"
   },
   {
    "name": "semester",
    "label": "Семестр",
    "query": "SELECT reverse(substring(reverse(discipline_name) FROM 1 FOR position(' ' IN reverse(discipline_name)) - 1)) FROM uploaded_db db\nJOIN discipline d ON db.discipline_id = d.discipline_id\nWHERE uploaded_db_id = $uploaded_db_id"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 }, "options": { "content": "# Дашборд по группам" } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 60, "w": 5, "x": 19, "y": 0 } },
  {
   "title": "Дисциплина",
   "type": "text",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 2 },
   "options": {
    "content": "# \"$discipline\", $semester семестр"
   }
  },
  {
   "title": "Диаграмма распределения оценок по выбранным группам",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT rating AS \"Оценка\", COUNT(*) AS \"Количество студентов с оценкой\"\r\nFROM (\r\n  SELECT rating FROM uploaded_db_result dbr\r\n  JOIN study_group sg ON dbr.study_group_id = sg.study_group_id\r\n  WHERE study_group_name = ANY(ARRAY[${group_name:sqlstring}]) AND uploaded_db_id = $uploaded_db_id\r\n  GROUP BY rating, student_id\r\n)\r\nGROUP BY rating\r\nORDER BY\r\n  CASE rating\r\n        WHEN 'отл.' THEN 1\r\n        WHEN 'хор.' THEN 2\r\n        WHEN 'удовл.' THEN 3\r\n        WHEN 'неудовл.' THEN 4\r\n        WHEN 'неявка' THEN 5\r\n        ELSE 6\r\n    END;"
    }
   ]
  },
  {
   "title": "Средний итоговый балл",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(total_score) FROM uploaded_db_result dbr\r\nJOIN study_group sg ON dbr.study_group_id = sg.study_group_id\r\nWHERE study_group_name = ANY(ARRAY[${group_name:sqlstring}]) AND uploaded_db_id = $uploaded_db_id"
    }
   ]
  },
  {
   "title": "Посещаемость по выбранным группам",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE WHEN SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END) = 0 THEN NULL\r\n\tELSE ROUND(SUM(CASE WHEN presence = true THEN 1 ELSE 0 END) * 100.0 / SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END), 2) END AS student_presence_percent\r\nFROM group_db_presence\r\nWHERE study_group_name = ANY(ARRAY[${group_name:sqlstring}]) AND uploaded_db_id = $uploaded_db_id"
    }
   ]
  },
  {
   "title": "Таблица успеваемости по группам",
   "type": "table",
   "gridPos": { "h": 25, "w": 19, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tmain.study_group_name as \"Название группы\",\r\n\tteacher_name as \"Преподаватели\",\r\n\tstudents_count as \"Количество студентов\",\r\n\tgroup_presence.group_presence_percent as \"Процент посещаемости\",\r\n\tavg_total_score as \"Средний итоговый балл\"\r\nFROM (\r\n\tSELECT study_group_id, study_group_name, AVG(total_score) as avg_total_score, COUNT(*) as students_count \r\n\tFROM (\r\n\t\tSELECT dbr.study_group_id, total_score, study_group_name, student_id FROM uploaded_db_result dbr\r\n\t\tJOIN study_group sg ON dbr.study_group_id = sg.study_group_id\r\n\t\tWHERE uploaded_db_id = $uploaded_db_id AND study_group_name = ANY(ARRAY[${group_name:sqlstring}])\r\n\t\tGROUP BY student_id, dbr.study_group_id, total_score, study_group_name, student_id\r\n\t)\r\n\tGROUP BY study_group_id, study_group_name\r\n) main\r\nJOIN (\r\n\tSELECT\r\n\t\tstudy_group_id,\r\n\t\tCASE WHEN SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END) = 0 THEN NULL\r\n\t\tELSE ROUND(SUM(CASE WHEN presence = true THEN 1 ELSE 0 END) * 100.0 / \r\n    SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END), 2) END AS group_presence_percent\r\n\tFROM group_db_presence\r\n\tWHERE uploaded_db_id = $uploaded_db_id AND study_group_name = ANY(ARRAY[${group_name:sqlstring}])\r\n\tGROUP BY study_group_id\r\n) group_presence ON main.study_group_id = group_presence.study_group_id\r\nJOIN study_group sd ON main.study_group_id = sd.study_group_id\r\nJOIN teacher t ON sd.teacher_id = t.teacher_id"
    }
   ]
  },
  {
   "title": "Студенты",
   "type": "table",
   "gridPos": { "h": 22, "w": 19, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tmain.student_id as \"ID студента\",\r\n\tstudent_name as \"ФИО студента\",\r\n\tgroup_names as \"Группа\",\r\n\tstudent_presence.student_presence_percent as \"Процент посещаемости\",\r\n\ttotal_score as \"Итоговый балл\"\r\nFROM (\r\n\tSELECT s.student_id, s.student_name, STRING_AGG(study_group_name, ', ') as group_names, total_score FROM uploaded_db_result dbr\r\n\tJOIN student s ON dbr.student_id = s.student_id\r\n\tJOIN study_group sg ON dbr.study_group_id = sg.study_group_id\r\n\tWHERE uploaded_db_id = $uploaded_db_id AND study_group_name = ANY(ARRAY[${group_name:sqlstring}])\r\n\tGROUP BY s.student_id, total_score\r\n\t ) main\r\nJOIN (\r\n\tSELECT\r\n\t\tstudent_id,\r\n\t\tCASE WHEN SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END) = 0 THEN NULL\r\n\t\tELSE ROUND(SUM(CASE WHEN presence = true THEN 1 ELSE 0 END) * 100.0 / SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END), 2) END AS student_presence_percent,\r\n\t\tuploaded_db_id\r\n\tFROM student_db_presence\r\n\tWHERE uploaded_db_id = $uploaded_db_id AND study_group_name = ANY(ARRAY[${group_name:sqlstring}])\r\n\tGROUP BY student_id, uploaded_db_id\r\n) student_presence ON main.student_id = student_presence.student_id"
    }
   ]
  }
 ]
}