{
 "title": "Дашборд по нарпавлениям подготовки",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uploaded_db_id",
    "label": "Загруженная БД",
    "query": "select uploaded_db_id from uploaded_db"
   },
   {
    "name": "study_direction",
    "label": "Направление подготовки",
    "query": "SELECT study_direction_name FROM study_direction"
   },
   {
    "name": "discipline",
    "label": "Дисциплина",
    "query": "SELECT reverse(substring(reverse(discipline_name) FROM position(' ' IN reverse(discipline_name)) + 1)) FROM uploaded_db db\nJOIN discipline d ON db.discipline_id = d.discipline_id\nWHERE uploaded_db_id = $uploaded_db_id"
   },
   {
    "name": "semester",
    "label": "Семестр",
    "query": "SELECT reverse(substring(reverse(discipline_name) FROM 1 FOR position(' ' IN reverse(discipline_name)) - 1)) FROM uploaded_db db\nJOIN discipline d ON db.discipline_id = d.discipline_id\nWHERE uploaded_db_id = $uploaded_db_id"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# Дашборд по направлениям подготовки"
   }
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 53, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Дисциплина",
   "type": "text",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 2 },
   "options": {
    "content": "# \"$discipline\", $semester семестр"
   }
  },
  {
   "title": "Диаграмма распределения оценок по выбранным направлениям",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT rating AS \"Оценка\", COUNT(*) AS \"Количество студентов с оценкой\"\r\nFROM (\r\n  SELECT rating FROM uploaded_db_result dbr\r\n  JOIN study_direction sd ON dbr.study_direction_id = sd.study_direction_id\r\n  WHERE study_direction_name = ANY(ARRAY[${study_direction:sqlstring}]) AND uploaded_db_id = $uploaded_db_id\r\n  GROUP BY rating, student_id\r\n)\r\nGROUP BY rating\r\nORDER BY\r\n  CASE rating\r\n        WHEN 'отл.' THEN 1\r\n        WHEN 'хор.' THEN 2\r\n        WHEN 'удовл.' THEN 3\r\n        WHEN 'неудовл.' THEN 4\r\n        WHEN 'неявка' THEN 5\r\n        ELSE 6\r\n    END;"
    }
   ]
  },
  {
   "title": "Средний итоговый балл",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(total_score) FROM uploaded_db_result dbr\r\nJOIN study_direction sd ON dbr.study_direction_id = sd.study_direction_id\r\nWHERE study_direction_name = ANY(ARRAY[${study_direction:sqlstring}]) AND uploaded_db_id = $uploaded_db_id"
    }
   ]
  },
  {
   "title": "Посещаемость",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE WHEN SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END) = 0 THEN NULL\r\n\tELSE ROUND(SUM(CASE WHEN presence = true THEN 1 ELSE 0 END) * 100.0 / SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END), 2) END AS student_presence_percent\r\nFROM direction_db_presence\r\nWHERE study_direction_name = ANY(ARRAY[${study_direction:sqlstring}]) AND uploaded_db_id = $uploaded_db_id"
    }
   ]
  },
  {
   "title": "Таблица успеваемости по направлениям",
   "type": "table",
   "gridPos": { "h": 22, "w": 17, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tstudy_direction_name as \"Направление подготовки\",\r\n\tstudents_count as \"Количество студентов\",\r\n\tdirection_presence.direction_presence_percent as \"Процент посещаемости\",\r\n\tavg_total_score as \"Средний итоговый балл\"\r\nFROM (\r\n\tSELECT study_direction_id, study_direction_name, AVG(total_score) as avg_total_score, COUNT(*) as students_count \r\n\tFROM (\r\n\t\tSELECT dbr.study_direction_id, total_score, study_direction_name, student_id FROM uploaded_db_result dbr\r\n\t\tJOIN study_direction sd ON dbr.study_direction_id = sd.study_direction_id\r\n\t\tWHERE uploaded_db_id = $uploaded_db_id AND study_direction_name = ANY(ARRAY[${study_direction:sqlstring}])\r\n\t\tGROUP BY student_id, dbr.study_direction_id, total_score, study_direction_name, student_id\r\n\t)\r\n\tGROUP BY study_direction_id, study_direction_name\r\n) main\r\nJOIN (\r\n\tSELECT\r\n\t\tstudy_direction_id,\r\n\t\tCASE WHEN SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END) = 0 THEN NULL\r\n\t\tELSE ROUND(SUM(CASE WHEN presence = true THEN 1 ELSE 0 END) * 100.0 / \r\n    SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END), 2) END AS direction_presence_percent\r\n\tFROM direction_db_presence\r\n\tWHERE uploaded_db_id = $uploaded_db_id AND study_direction_name = ANY(ARRAY[${study_direction:sqlstring}])\r\n\tGROUP BY study_direction_id\r\n) direction_presence ON main.study_direction_id = direction_presence.study_direction_id"
    }
   ]
  },
  {
   "title": "Студенты",
   "type": "table",
   "gridPos": { "h": 17, "w": 17, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tmain.student_id as \"ID студента\",\r\n\tstudent_name as \"ФИО студента\",\r\n\tstudy_direction_name as \"Направление подготовки\",\r\n\tstudent_presence.student_presence_percent as \"Процент посещаемости\",\r\n\ttotal_score as \"Итоговый балл\"\r\nFROM (\r\n\tSELECT s.student_id, s.student_name, study_direction_name, total_score FROM uploaded_db_result dbr\r\n\tJOIN student s ON dbr.student_id = s.student_id\r\n\tJOIN study_direction sd ON dbr.study_direction_id = sd.study_direction_id\r\n\tWHERE uploaded_db_id = $uploaded_db_id AND study_direction_name = ANY(ARRAY[${study_direction:sqlstring}])\r\n\tGROUP BY s.student_id, total_score, study_direction_name\r\n\t) main\r\nJOIN (\r\n\tSELECT\r\n\t\tstudent_id,\r\n\t\tCASE WHEN SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END) = 0 THEN NULL\r\n\t\tELSE ROUND(SUM(CASE WHEN presence = true THEN 1 ELSE 0 END) * 100.0 / SUM(CASE WHEN presence = true OR presence = false THEN 1 ELSE 0 END), 2) END AS student_presence_percent,\r\n\t\tuploaded_db_id\r\n\tFROM student_db_presence\r\n\tWHERE uploaded_db_id = $uploaded_db_id AND study_direction_name = ANY(ARRAY[${study_direction:sqlstring}])\r\n\tGROUP BY student_id, uploaded_db_id\r\n) student_presence ON main.student_id = student_presence.student_id"
    }
   ]
  }
 ]
}